version: '3.4'
services:
  bootnode:
    build:
      dockerfile: ./images/lighthouse.Dockerfile
    expose:
      - 4242/tcp
      - 4242/udp
    volumes:
      - ./genesis_data:/data
      - ./genesis_config:/config
      - ./scripts:/scripts
    entrypoint:
      "/scripts/bootnode.sh"
    depends_on:
      genesis-generator:
        condition: service_completed_successfully
  genesis-generator:
    image: ethpandaops/ethereum-genesis-generator:latest
    entrypoint: 
      "/scripts/genesis_generator.sh"
    volumes:
      - ./scripts:/scripts
      - ./genesis_data:/data
      - ./validator_data:/validator_data
      - ./genesis_config:/config
    expose:
      - 8000
  beacon:
    build:
      dockerfile: ./images/lighthouse.Dockerfile
    deploy:
      # noinspection ComposeUnknownValues
      replicas: ${NUMBER_OF_NODES}
    expose:
      - 5052
      - 9000/tcp
      - 9000/udp
    volumes:
      - ./scripts:/scripts
      - ./genesis_data:/data
      - ./genesis_config:/config
    entrypoint:
      "/scripts/beacon.sh"
    depends_on:
      bootnode:
        condition: service_started
  execution:
    image: ethereum/client-go
    deploy:
      # noinspection ComposeUnknownValues
      replicas: ${NUMBER_OF_NODES}
    expose:
      - 8545
      - 8551
    volumes:
      - ./scripts:/scripts
      - ./genesis_data:/data
      - ./genesis_config:/config
    entrypoint:
      "/scripts/execution.sh"
    depends_on:
      genesis-generator:
        condition: service_completed_successfully
  validator:
    build:
      dockerfile: ./images/lighthouse.Dockerfile
    env_file: ./genesis_config/values.env
    deploy:
      # noinspection ComposeUnknownValues
      replicas: ${NUMBER_OF_NODES}
    expose:
      - 5052
    volumes:
      - ./scripts:/scripts
      - ./genesis_data:/data
      - ./validator_data:/validator_data
    entrypoint:
      "/scripts/validator.sh"
    depends_on:
      genesis-generator:
        condition: service_completed_successfully
  proxy:
    image: seananderson33/json_rpc_snoop:capella
    deploy:
      # noinspection ComposeUnknownValues
      replicas: ${NUMBER_OF_NODES}
    entrypoint:
      "/scripts/proxy.sh"
    expose:
      - 8551
    volumes:
      - ./scripts:/scripts
  mock-relay:
    image: seananderson33/mock-relay:latest
    deploy:
      # noinspection ComposeUnknownValues
      replicas: ${NUMBER_OF_NODES}
    entrypoint:
      "/scripts/mock-relay.sh"
    expose:
      - 8650
    volumes:
      - ./scripts:/scripts
      - ./genesis_data:/data
      - ./genesis_config:/config
